// Conteúdo editorial provisório. Substitua aqui após aprovar a estrutura.
window.JOTA_CONTENT = {
  whatsapp: '5581995569112', // Link público do Instagram. Confirmar antes de publicar.
  instagram: 'https://www.instagram.com/jotaesportivo/',
  cases: [
    { id: 'rc', name: 'RC Goleiros', category: 'Futsal · Conteúdo & comunidade', image: 'assets/case-rc.webp', title: 'A defesa ganha\nprotagonismo.', metric: '+ DE 2 MI', metricLabel: 'de visualizações no Keeper Combat', source: 'https://www.instagram.com/rcgoleiros/p/DZLuYpvspE_/', objective: 'Levar a energia dos goleiros para além da quadra.', work: 'Conteúdo e presença digital no universo dos goleiros. Referência visual: publicação compartilhada no perfil da JOTA.', result: 'A publicação pública do Keeper Combat apresenta mais de 2 milhões de visualizações. Período, escopo da atuação e atribuição da JOTA serão detalhados na versão final.', note: 'Base editorial · escopo a validar' },
    { id: 'escola', name: 'Escola 360 Pro', category: 'Educação esportiva · Presença digital', image: 'assets/case-escola.webp', title: 'Conhecimento que\nentra em campo.', metric: '360°', metricLabel: 'um novo olhar para o negócio esportivo', source: 'https://www.instagram.com/escola360pro/reel/DZNUnK_AE9Q/', objective: 'Conectar conhecimento, profissionais e negócios do esporte.', work: 'Referência de conteúdo publicada em colaboração e exibida no perfil da JOTA. Entregas e estratégia aguardam validação.', result: 'Espaço reservado para os resultados aprovados do projeto. Nenhum indicador de desempenho é atribuído a este case nesta versão.', note: 'Base editorial · resultados a inserir' },
    { id: 'campo', name: 'Dentro do jogo', category: 'Bastidores · Produção esportiva', image: 'assets/bastidores.webp', title: 'A melhor história\ncomeça de perto.', metric: 'EM CAMPO', metricLabel: 'o esporte visto de dentro', source: 'https://www.instagram.com/rcgoleiros/reel/DZACbDjRKec/', objective: 'Capturar a experiência real de quem vive o esporte.', work: 'Uma prévia da linguagem de bastidores da marca: câmera próxima, contexto esportivo e pessoas no centro.', result: 'Composição demonstrativa da estrutura de um projeto. Cliente, entregas e resultados serão substituídos pelo case definitivo.', note: 'Projeto demonstrativo' }
  ]
};
